In [1]:
import numpy as np

In [2]:
## Recreating problems 1 through 10 of Part I.

In [3]:
## Create matrices A, B, C, D.
a = np.array([[2,3],[4,9]])
b = np.array([[-2,-6],[5,15]])
c = np.array([[7,1,4],[-1,0,4]])
d = np.array([[1],[-1]])

In [4]:
# Part I, Problem 1:
a + b

array([[ 0, -3],
       [ 9, 24]])

In [5]:
# Part I, Problem 2:

## You can't really recreate this in Python with a generic
## constant k, but I'll assume k = 2.

2 * c

array([[14,  2,  8],
       [-2,  0,  8]])

In [6]:
# Part I, Problem 3:

a - b

array([[ 4,  9],
       [-1, -6]])

In [7]:
# Part I, Problem 4:

b + d

## Wait, but Python didn't throw an error! Unfortunately,
## Python assumes that I wanted to take each column of B
## and add D to each column. If you have time, play around
## with this and see what dimensions throw an error and
## which do not.

array([[-1, -5],
       [ 4, 14]])

In [8]:
# Part I, Problem 5:

np.matmul(a,b)

## WARNING: If you do a * b, Python assumes you want
## *elementwise* multiplication. Much like a + b, Python
## takes each pair of corresponding elements and returns
## the multiple of those.

array([[ 11,  33],
       [ 37, 111]])

In [9]:
# Part I, Problem 6:

np.matmul(b,a)

array([[-28, -60],
       [ 70, 150]])

In [10]:
# Part I, Problem 7:

np.matmul(d,a)

## Woo! We got an error - so at least Python won't
## let us make mistakes here!

ValueError: shapes (2,1) and (2,2) not aligned: 1 (dim 1) != 2 (dim 0)

In [11]:
# Part I, Problem 8:

np.matmul(a,d)

array([[-1],
       [-5]])

In [12]:
# Part I, Problem 9:

np.transpose(c)

array([[ 7, -1],
       [ 1,  0],
       [ 4,  4]])

In [13]:
# Part I, Problem 10:

print np.transpose(3*d)

print 3*np.transpose(d) ## Although not necessary since
## we know we should get the same value, I added problem
## 11 to show that the order doesn't matter within Python.

[[ 3 -3]]
[[ 3 -3]]


In [14]:
## Part II, Problem 1:

np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [15]:
## Part II, Problem 2:
np.linalg.det(a)

6.0

In [16]:
## Part II, Problem 3:
np.linalg.inv(a)

array([[ 1.5       , -0.5       ],
       [-0.66666667,  0.33333333]])

In [17]:
## Part II, Problem 4:
print np.matmul(a,np.linalg.inv(a)) ## A x A^(-1)
print np.matmul(np.linalg.inv(a),a) ## A^(-1) x A

## These values are a little messy... there's a lot of
## trailing zeroes and even though we know that any
## number with (e-16) at the end is going to basically
## be zero, we might want to clean this up.

[[  1.00000000e+00   1.11022302e-16]
 [  0.00000000e+00   1.00000000e+00]]
[[  1.00000000e+00   8.88178420e-16]
 [  0.00000000e+00   1.00000000e+00]]


In [18]:
## Part II, Problem 4, continued:
print np.round(np.matmul(a,np.linalg.inv(a)),3)
print np.round(np.matmul(np.linalg.inv(a),a),3)

## Much better!! We used np.round(matrix,3) so that we'd
## round to three decimals. You can choose whatever you'd
## like, but for this particular purpose, three decimals 
## is going to be sufficient.

## Now we can reasonably conclude that A x A^(-1) and
## A^(-1) x A both equal the identity matrix. If we
## wanted to take this one step further...

[[ 1.  0.]
 [ 0.  1.]]
[[ 1.  0.]
 [ 0.  1.]]


In [19]:
## Part II, Problem 4, continued:

print np.matmul(a,np.linalg.inv(a)) == np.eye(2)

## It might be good to round here, **provided that you
## are comfortable rounding in this context!**

print np.round(np.matmul(a,np.linalg.inv(a)),3) == np.eye(2)

## You can repeat this for A^(-1) x A to be sure.

[[ True False]
 [ True False]]
[[ True  True]
 [ True  True]]


In [20]:
## Part II, Problem 5

np.linalg.det(b)

## Basically zero.

-1.6653345369377366e-15

In [21]:
## Part II, Problem 6

np.linalg.inv(b)

## Uhh, these are really, really, really large numbers.
## Something seems suspicious here.

array([[ -9.00719925e+15,  -3.60287970e+15],
       [  3.00239975e+15,   1.20095990e+15]])

In [22]:
## Part II, Problem 6 (additional exploration)

## We know that B x B^(-1) should equal I_2.

np.matmul(b,np.linalg.inv(b))

## Welp. It didn't. (This is caused by floating-point
## arithmetic. We'll discuss this in class, but basically
## we arrive at the conclusion that this inverse is
## invalid or doesn't really exist.)

array([[ 0., -1.],
       [ 0.,  2.]])

In [23]:
## Part II, Problem 7

## Answer: The determinant in problem 2 was a positive
## number and gave us a valid inverse, whereas the
## determinant in problem 5 was basically zero and there
## were problems with finding the matrix inverse. Maybe
## the determinant needs to be positive or just needs to
## not be zero for the inverse to exist.

## Real answer: If *and only if* the determinant of a 
## matrix is not zero, then the inverse does exist.