In [1]:
import numpy as np

In [2]:
weather = np.array([[0.6,0.4,0.3],[0.3,0.4,0.3],[0.1,0.2,0.4]])

In [3]:
weather

array([[ 0.6,  0.4,  0.3],
       [ 0.3,  0.4,  0.3],
       [ 0.1,  0.2,  0.4]])

In [19]:
snowy = np.array([0.2,0.8,0])

In [20]:
snowy

array([ 0.2,  0.8,  0. ])

In [21]:
np.matmul(weather,snowy)

array([ 0.44,  0.38,  0.18])

In [13]:
def repeated_matmul(transition_matrix, step, state_vector):
    print np.matmul(np.linalg.matrix_power(transition_matrix,step), state_vector)

In [22]:
repeated_matmul(weather,1,snowy)

[ 0.44  0.38  0.18]


In [23]:
repeated_matmul(weather,2,snowy)

[ 0.47   0.338  0.192]


In [24]:
repeated_matmul(weather,5,snowy)

[ 0.476084  0.333338  0.190578]


In [25]:
repeated_matmul(weather,50,snowy)

[ 0.47619048  0.33333333  0.19047619]


In [27]:
repeated_matmul(weather,10000,snowy)

[ 0.47619048  0.33333333  0.19047619]
