In [1]:
import pandas as pd
import numpy as np
import os
from matplotlib import pyplot as plt
import numpy as np
import math
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA 

votes_file = 'votes.csv'
airport_file = 'airport.csv'

# Case #1: Congressional Voting Data

After you've downloaded the data from the repository, go ahead and load it with Pandas and handle any preprocessing that it may need. 

In [2]:
votes = pd.read_csv(votes_file)
airport = pd.read_csv(airport_file)

In [3]:
def eda(dataframe):
    
    print "missing values \n", dataframe.isnull().sum()## count number of null values per column
    print ''
    print "dataframe types \n", dataframe.dtypes       ## list data type of each column
    print ''
    print "dataframe shape \n", dataframe.shape        ## rows by columns
    print ''
    print "dataframe describe \n", dataframe.describe()## stats -- mean, min, max, etc.. 
    print ''
    print 'unique values in series:\n'
    for item in dataframe:                             ## count number of unique values per column
        print item, '\t\t\t', dataframe[item].nunique()
    print ''
    print 'num duplicates:', dataframe.duplicated().sum() ## df.drop_duplicates() to remove dupes

In [4]:
eda(votes)

missing values 
Unnamed: 0      0
Class           0
V1             12
V2             48
V3             11
V4             11
V5             15
V6             11
V7             14
V8             15
V9             22
V10             7
V11            21
V12            31
V13            25
V14            17
V15            28
V16           104
dtype: int64

dataframe types 
Unnamed: 0     int64
Class         object
V1            object
V2            object
V3            object
V4            object
V5            object
V6            object
V7            object
V8            object
V9            object
V10           object
V11           object
V12           object
V13           object
V14           object
V15           object
V16           object
dtype: object

dataframe shape 
(435, 18)

dataframe describe 
       Unnamed: 0
count  435.000000
mean   218.000000
std    125.717938
min      1.000000
25%    109.500000
50%    218.000000
75%    326.500000
max    435.000000

unique values in series:


In [5]:
# drop unnecessary column from csv
del(votes['Unnamed: 0'])
votes.dropna(axis=0,inplace=True)

Next, create the covariance matrix from the standardized x-values and decompose these values to find the eigenvalues and eigenvectors

In [27]:
# convert class to 0, 1
votes['Class'] = votes.Class.replace('republican','1')
votes['Class'] = votes.Class.replace('democrat','0')
votes['Class'] = votes['Class'].astype(float)

for column in votes.columns.drop('Class'):
    votes[column] = votes[column].replace('y','1')
    votes[column] = votes[column].replace('n','0')
    votes[column] = votes[column].replace('NaN',np.NaN)    
    votes[column] = votes[column].astype(float)

cov_mat=np.cov(votes)
cov_mat

array([[ 0.26470588,  0.11029412, -0.01470588, ..., -0.01102941,
         0.05147059, -0.05147059],
       [ 0.11029412,  0.26470588, -0.17279412, ...,  0.13602941,
         0.13602941, -0.13602941],
       [-0.01470588, -0.17279412,  0.26470588, ..., -0.17647059,
        -0.17647059,  0.11397059],
       ..., 
       [-0.01102941,  0.13602941, -0.17647059, ...,  0.24264706,
         0.11764706,  0.00735294],
       [ 0.05147059,  0.13602941, -0.17647059, ...,  0.11764706,
         0.24264706,  0.00735294],
       [-0.05147059, -0.13602941,  0.11397059, ...,  0.00735294,
         0.00735294,  0.24264706]])

In [31]:
from numpy import linalg
linalg.eig(cov_mat)[0]

array([  2.93710457e+01 +0.00000000e+00j,
         5.83689464e+00 +0.00000000e+00j,
         4.09805310e+00 +0.00000000e+00j,
         3.49646056e+00 +0.00000000e+00j,
         3.10030390e+00 +0.00000000e+00j,
         2.52303559e+00 +0.00000000e+00j,
         1.89939893e+00 +0.00000000e+00j,
         1.82398438e+00 +0.00000000e+00j,
         1.34173651e+00 +0.00000000e+00j,
         1.23646072e+00 +0.00000000e+00j,
         1.11351066e+00 +0.00000000e+00j,
         1.17870448e+00 +0.00000000e+00j,
         8.67869655e-01 +0.00000000e+00j,
         6.77370161e-01 +0.00000000e+00j,
         4.37825520e-01 +0.00000000e+00j,
         1.88521993e-01 +0.00000000e+00j,
         2.79600224e-15 +5.53480240e-16j,
         2.79600224e-15 -5.53480240e-16j,
        -2.38291880e-15 +5.73777207e-16j,
        -2.38291880e-15 -5.73777207e-16j,
        -1.89286695e-15 +0.00000000e+00j,
        -3.04044071e-16 +1.83004324e-15j,
        -3.04044071e-16 -1.83004324e-15j,
         1.45040114e-15 +9.3681462

In [26]:
from numpy import array, dot, mean, std, empty, argsort
from numpy.linalg import eigh, solve
from numpy.random import randn
from matplotlib.pyplot import subplots, show



import numpy

def principalComponents(matrix):
    # Columns of matrix correspond to data points, rows to dimensions.

    deviationMatrix = (matrix.T - numpy.mean(matrix, axis=1)).T
    covarianceMatrix = numpy.cov(deviationMatrix)
    eigenvalues, principalComponents = numpy.linalg.eig(covarianceMatrix)

    # sort the principal components in decreasing order of corresponding eigenvalue
    indexList = numpy.argsort(-eigenvalues)
    eigenvalues = eigenvalues[indexList]
    principalComponents = principalComponents[:, indexList]

    return eigenvalues, principalComponents

principalComponents(votes)

# cred
# https://jeremykun.com/category/probability-theory/page/6/?iframe=true&preview=true%2Ffeed%2F


(array([  2.93710457e+01 +0.00000000e+00j,
          5.83689464e+00 +0.00000000e+00j,
          4.09805310e+00 +0.00000000e+00j,
          3.49646056e+00 +0.00000000e+00j,
          3.10030390e+00 +0.00000000e+00j,
          2.52303559e+00 +0.00000000e+00j,
          1.89939893e+00 +0.00000000e+00j,
          1.82398438e+00 +0.00000000e+00j,
          1.34173651e+00 +0.00000000e+00j,
          1.23646072e+00 +0.00000000e+00j,
          1.17870448e+00 +0.00000000e+00j,
          1.11351066e+00 +0.00000000e+00j,
          8.67869655e-01 +0.00000000e+00j,
          6.77370161e-01 +0.00000000e+00j,
          4.37825520e-01 +0.00000000e+00j,
          1.88521993e-01 +0.00000000e+00j,
          2.41281064e-15 +1.27733570e-15j,
          2.41281064e-15 -1.27733570e-15j,
          2.01441849e-15 +0.00000000e+00j,
          1.39346970e-15 +0.00000000e+00j,
          8.19202175e-16 +3.25763376e-17j,
          8.19202175e-16 -3.25763376e-17j,
          7.69351799e-16 +1.33027814e-15j,
          7

Now, let's check the eigenvalues: 

In [ ]:
evals, evecs = np.linalg.eigh(cov_mat)
    

sns.pairplot(subjective, kind='reg')
plt.show()

subjective_pca = PCA(n_components=5)
subjective_pca.fit(subjective.values)

subj_components = subjective_pca.components_
subj_components


subj_exp_var_eigenvals = subjective_pca.explained_variance_
subj_exp_var_pct = subjective_pca.explained_variance_ratio_

print 'eigenvalues:', subj_exp_var_eigenvals
print ''
print 'explained variance pct:', subj_exp_var_pct
print ''
print subj_exp_var_pct.sum()

And the eigenvectors: 

To find the principal components, find the eigenpairs, and sort them from highest to lowest. 

Now, calculate the explained variance. Recall the methods we learned in the lesson! 

Now, calculate the explained variance and the Cumulative explained variance

Now, find and interperet the principal components

Now, repeat the process with sklearn.
http://scikit-learn.org/stable/modules/generated/sklearn.decomposition.PCA.html

# Case #2: Airport Delays

In this case, we want to look at this dataset in an unsupervised manner. 

In [6]:
air = pd.read_csv('datasets/airport.csv')

In [8]:
air.head()
air.shape

(841, 15)

Then, standardize the features for analysis

Next, create the covariance matrix from the standardized x-values and decompose these values to find the eigenvalues and eigenvectors

Then, check your eigenvalues and eigenvectors:

To find the principal componants, find the eigenpairs, and sort them from highest to lowest. 

Next, Calculate the explained variance

Finally, conduct the PCA - use the results about to guide your selection of "n" componants